name: Feature Request
description: Suggest a new feature or enhancement for LLMRouter
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Please confirm you have completed the following steps
      options:
        - label: I have searched the existing issues and this feature has not been requested yet
          required: true
        - label: I believe this is a feature request, not a bug report or question
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of LLMRouter does this feature relate to?
      options:
        - New Router Implementation
        - Existing Router Enhancement
        - CLI / Command Line Interface
        - Data Generation Pipeline
        - Training / Evaluation
        - Chat Interface
        - Documentation
        - Performance / Optimization
        - API / Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature and what problem it would solve...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the use case or scenario where this feature would be helpful
      placeholder: |
        As a [type of user], I want [goal] so that [reason].

        Example scenario:
        ...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: If you have ideas on how this could be implemented, please share them
      placeholder: |
        Possible approach:
        1. ...
        2. ...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here
